src/Siriru/GSBundle/Entity/ChampionshipTournament.php
<?php

namespace Siriru\GSBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="championship_tournament")
 */
class ChampionshipTournament extends GoldsprintType
{
    /**
     * @ORM\Column(type="integer")
     */
    protected $nb_championship_round = 2;

    /**
     * @ORM\Column(type="integer")
     */
    protected $nb_qualified_player = 8;

    public function __construct()
    {
        parent::__construct();
        $this->name = "championship-tournament";
    }

    /**
     * @param mixed $nb_championship_round
     */
    public function setNbChampionshipRound($nb_championship_round)
    {
        $this->nb_championship_round = $nb_championship_round;
    }

    /**
     * @return mixed
     */
    public function getNbChampionshipRound()
    {
        return $this->nb_championship_round;
    }

    /**
     * @param mixed $nb_qualified_player
     */
    public function setNbQualifiedPlayer($nb_qualified_player)
    {
        $this->nb_qualified_player = $nb_qualified_player;
    }

    /**
     * @return mixed
     */
    public function getNbQualifiedPlayer()
    {
        return $this->nb_qualified_player;
    }

    public function setLastStep()
    {
        if ($this->getGoldsprint()->getPlayers()->count() == 0) $this->last_step = 1;
        //on ajoute 1 pour la finale des perdants
        else $this->last_step = 1 + log($this->nb_qualified_player)/log(2) + $this->nb_championship_round;

        return $this;
    }

    public function start()
    {
        $players = $this->getGoldsprint()->getPlayers()->toArray();
        $this->createRound($players);
    }

    public function updateFirstRuns($players)
    {
        shuffle($players);
        foreach($this->getRuns() as $run) {
            //uniquement au step 1 et si le run est en solo
            if($run->getStep() == 1 and $run->getPlayer2() == null) {
                $run->setPlayer2(array_pop($players));
            }
        }
        $this->createRound($players);
    }

    public function nextStep()
    {
        //on augmente le step de 1
        $this->setStep($this->step+1);
        //si le gs n'est pas finito
        if(!$this->getGoldsprint()->getFinished()) {
            //si on est encore dans la phase championnat on refait un round avec tout le monde
            if($this->step <= $this->nb_championship_round) {
                $players = $this->getGoldsprint()->getPlayers()->toArray();
                $this->createRound($players);
            }
            //si le step est supérieur au nombre de round du championnat préliminaire, on passe au tournoi
            elseif($this->step == $this->nb_championship_round + 1) {
                $championship_results = array_slice($this->getChampionshipResults(), 0, $this->nb_qualified_player, true);
                $qualified_players = array();
                foreach($championship_results as $result) {
                    $qualified_players[] = $result['object'];
                }
                $this->createRound($qualified_players);
            }
            else {
                $players = $this->getQualifiedPlayer($this->step - 1);
                //si c'est la finale, on crée la finale des perdants et on cloture le tournoi
                if($this->step == $this->last_step - 1) {
                    $loosers = array();
                    foreach($this->getRunsAtStep($this->step - 1) as $run) {
                        $loosers[] = $run->getLooser();
                    }
                    $this->createRound($loosers);
                    $this->setStep($this->step+1);
                    $this->createRound($players);
                    $this->getGoldsprint()->setFinished(true);
                }
                else {
                    $this->createRound($players);
                }
            }
        }
    }

    public function isStepOver()
    {
        if($this->step <= $this->nb_championship_round) {
            foreach($this->getRunsAtStep($this->step) as $run) {
                if($run->getTime1() === null or $run->getTime2() === null) return false;
            }
        }
        else {
            foreach($this->getRunsAtStep($this->step) as $run) {
                if($run->getWinner() === null) return false;
            }
        }
        return true;
    }

    private function getQualifiedPlayer($step)
    {
        $players = array();
        foreach($this->getRunsAtStep($step) as $run) {
            $players[] = $run->getWinner();
        }
        return $players;
    }

    public function getChampionshipResults()
    {
        $results = array();
        $step = 1;
        //on regarde tous les runs du championnat
        while($step <= $this->nb_championship_round) {
            //on rempli un tableau qui contient en clé le nom du joueur, et qui contient l'objet player et tous ses temps.
            foreach($this->getRunsAtStep($step) as $run) {
                $player1 = $run->getPlayer1();
                $player2 = $run->getPlayer2();
                if(!array_key_exists($player1->getName(), $results)) {
                    $results[$player1->getName()] = array(
                        'object' => $player1,
                        'time' => array($run->getTime1())
                    );
                }
                else $results[$player1->getName()]['time'][] = $run->getTime1();

                if($player2 !== null) {
                    if(!array_key_exists($player2->getName(), $results)) {
                        $results[$player2->getName()] = array(
                            'object' => $player2,
                            'time' => array($run->getTime2())
                        );
                    }
                    else $results[$player2->getName()]['time'][] = $run->getTime2();
                }
            }
            $step++;
        }
        return $this->sortResults($results);
    }

    private function sortResults($results)
    {
        usort($results, function($player1, $player2) {
            $times1 = $player1['time']; usort($times1, array($this, 'sortTime'));
            $times2 = $player2['time']; usort($times2, array($this, 'sortTime'));

            for($i=0;$i<count($times1);$i++) {
                if($times1[$i] !== $times2[$i]) return ($times1[$i] > $times2[$i]) ? 1 : -1;
                elseif($times1[$i] === null) return 1;
                elseif($times2[$i] === null) return -1;
            }
            return 0;
        });
        return $results;
    }

    private function sortTime($time1, $time2)
    {
        if($time1 === $time2) return 0;
        if($time1 === null) return 1;
        if($time2 === null) return -1;
        return ($time1 > $time2) ? 1 : -1;
    }

    public function getTournamentResults()
    {
        $results = array();
        $step = $this->nb_championship_round + 1;
        while($step <= $this->last_step) {
            $temp = array();
            foreach($this->getRunsAtStep($step) as $run) {
                $temp[] = $run;
            }
            usort($temp, function($run1, $run2) {
                $time1 = $run1->getLooserTime();
                $time2 = $run2->getLooserTime();
                if ($time1 == $time2) {
                    return 0;
                }
                return ($time1 > $time2) ? -1 : 1;
            });

            foreach($temp as $run) {
                $results[] = $run->getLooser();
                if($step >= $this->last_step - 1) $results[] = $run->getWinner();
            }
            $step++;
            if($step == $this->last_step - 2) $step++;
        }

        return array_reverse($results);
    }

    public function getResults()
    {
        $results = array();
        $temp = $this->getTournamentResults();
        $end_of_championship = array_slice($this->getChampionshipResults(), $this->nb_qualified_player, null, true);
        foreach($end_of_championship as $result) {
            $temp[] = $result['object'];
        }
        $best_times = $this->getBestTimes();
        foreach($temp as $player) {
            if(array_key_exists($player->getName(), $best_times)) {
                $object = $player;
                $results[$player->getName()] = array();
                $results[$player->getName()]['object'] = $object;
                $results[$player->getName()]['time'] = $best_times[$player->getName()];
                if($player->getRecord() > $best_times[$player->getName()] or $player->getRecord() === null) $results[$player->getName()]['personal-record'] = true;
                else $results[$player->getName()]['personal-record'] = false;
                if($best_times[$player->getName()] === reset($best_times)) $results[$player->getName()]['goldsprint-record'] = true;
                else $results[$player->getName()]['goldsprint-record'] = false;
            }
        }

        return $results;
    }

    public function getBestTimes()
    {
        $results = array();
        foreach($this->runs as $run) {
            $results = $this->checkIfBestTime($results, $run->getPlayer1(), $run->getTime1());
            $results = $this->checkIfBestTime($results, $run->getPlayer2(), $run->getTime2());
        }
        asort($results);
        return $results;
    }

    private function checkIfBestTime($results, $player, $time)
    {
        if($time !== null) {
            if(!array_key_exists($player->getName(), $results)) $results[$player->getName()] = $time;
            else {
                if($results[$player->getName()] > $time) $results[$player->getName()] = $time;
            }
        }
        return $results;
    }
}

src/Siriru/GSBundle/Entity/Goldsprint.php
<?php

namespace Siriru\GSBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Siriru\GSBundle\Entity\GoldsprintRepository")
 * @ORM\Table(name="goldsprint")
 */
class Goldsprint
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $name;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $location;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $description;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $created;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $started;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $finished;

    /**
     * @ORM\OneToOne(targetEntity="GoldsprintType", mappedBy="goldsprint", cascade={"remove", "persist"})
     */
    protected $type;

    /**
     * @ORM\ManyToMany(targetEntity="Player")
     * @ORM\OrderBy({"name" = "ASC"})
     */
    protected $players;

    public function __construct()
    {
        $this->date = new \DateTime();
        $this->players = new ArrayCollection();
        $this->created = new \DateTime();
        $this->started = false;
        $this->finished = false;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Goldsprint
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set location
     *
     * @param string $location
     * @return Goldsprint
     */
    public function setLocation($location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Get location
     *
     * @return string 
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Goldsprint
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Add players
     *
     * @param \Siriru\GSBundle\Entity\Player $players
     * @return Goldsprint
     */
    public function addPlayer(Player $players)
    {
        $this->players[] = $players;

        return $this;
    }

    /**
     * Remove players
     *
     * @param \Siriru\GSBundle\Entity\Player $players
     */
    public function removePlayer(Player $players)
    {
        $this->players->removeElement($players);
    }

    /**
     * Get players
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPlayers()
    {
        return $this->players;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Goldsprint
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Goldsprint
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set started
     *
     * @param boolean $started
     * @return Goldsprint
     */
    public function setStarted($started)
    {
        $this->started = $started;

        return $this;
    }

    /**
     * Get started
     *
     * @return boolean 
     */
    public function getStarted()
    {
        return $this->started;
    }

    /**
     * Set finished
     *
     * @param boolean $finished
     * @return Goldsprint
     */
    public function setFinished($finished)
    {
        $this->finished = $finished;

        return $this;
    }

    /**
     * Get finished
     *
     * @return boolean 
     */
    public function getFinished()
    {
        return $this->finished;
    }

    /**
     * Set type
     *
     * @param \Siriru\GSBundle\Entity\GoldsprintType $type
     * @return Goldsprint
     */
    public function setType(GoldsprintType $type = null)
    {
        $this->type = $type;
        $this->type->setGoldsprint($this);
        return $this;
    }

    /**
     * Get type
     *
     * @return \Siriru\GSBundle\Entity\GoldsprintType 
     */
    public function getType()
    {
        return $this->type;
    }

    public function getOtherPlayers($players)
    {
        $results = new ArrayCollection();
        foreach($players as $player) {
            if(!$this->players->contains($player)) $results->add($player);
        }

        return $results;
    }
}

src/Siriru/GSBundle/Form/GSTimeType.php
<?php

namespace Siriru\GSBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Siriru\GSBundle\Form\DataTransformer\GSTimeToNumberTransformer;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class GSTimeType extends AbstractType
{
    /**
     * @var ObjectManager
     */
    private $om;

    /**
     * @param ObjectManager $om
     */
    public function __construct(ObjectManager $om)
    {
        $this->om = $om;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $transformer = new GSTimeToNumberTransformer($this->om);
        $builder->addViewTransformer($transformer);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'invalid_message' => 'Invalid',
        ));
    }

    public function getParent()
    {
        return 'text';
    }

    public function getName()
    {
        return 'gs_time';
    }
}

src/Siriru/GSBundle/Form/GoldsprintType.php
<?php

namespace Siriru\GSBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Doctrine\ORM\EntityRepository;

class GoldsprintType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('location')
            ->add('description')
            ->add('date')
            ->add('players', 'entity', array(
                'class' => 'SiriruGSBundle:Player',
                'query_builder' => function(EntityRepository $er) {
                    return $er->createQueryBuilder('p')
                        ->where('p.enabled = TRUE')
                        ->orderBy('p.name', 'ASC');
                    },
                'property' => 'name',
                'expanded' => true,
                'multiple' => true
            ));
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Siriru\GSBundle\Entity\Goldsprint'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'siriru_gsbundle_goldsprint';
    }
}

src/Siriru/GSBundle/Resources/views/Goldsprint/championship-results.html.twig
<table class="table table-bordered table-condensed table-striped table-hover">
    <thead>
    <tr>
        <th>Player</th>
        {% for i in 1..entity.type.step %}
            <th>Round {{ i }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for result in entity.type.results %}
    <tr>
        <td>{{ result.object }}</td>
        {% for time in result.time %}
            <td>{{ time | gstime }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
    </tbody>
</table>

src/Siriru/GSBundle/Resources/views/Goldsprint/championship-run.html.twig
<tr>
    <td data-time="{{ run.time1 }}" class="time" style="text-align: right; width: 20%;">{{ run.time1 | gstime }}</td>
    <td style="text-align: center; width: 30%;"><a href="{{ path('run_edit', {'id': run.id}) }}">{{ run.player1 }}</a></td>
    <td style="text-align: center; width: 30%;"><a href="{{ path('run_edit', {'id': run.id}) }}">{{ run.player2 }}</a></td>
    <td data-time="{{ run.time2 }}" class="time" style="text-align: left; width: 20%;">{{ run.time2 | gstime }}</td>
</tr>

src/Siriru/GSBundle/Resources/views/Goldsprint/championship-tournament-results.html.twig
<table class="table table-bordered table-hover table-condensed" style="width: 40%; margin: 0 auto;">
    {% for player, result in entity.type.results %}
        <tr>
            <td style="text-align: center;">{{ loop.index }}</td>
            <td style="text-align: center;">
                {% if loop.index == 1 %}{{ include('SiriruGSBundle:Utility:first.html.twig') }}
                {% elseif loop.index == 2 %}{{ include('SiriruGSBundle:Utility:second.html.twig') }}
                {% elseif loop.index == 3 %}{{ include('SiriruGSBundle:Utility:third.html.twig') }}
                {% endif %}
                {{ result['object'] }}
            </td>
            <td>
                {{ result['time'] | gstime }}
                {% if result['personal-record'] %}<span style="font-size: 7pt;" class="label label-default">PR</span>{% endif %}
                {% if result['goldsprint-record'] %}<span style="font-size: 7pt;" class="label label-primary">GR</span>{% endif %}
            </td>
        </tr>
    {% endfor %}
</table>

src/Siriru/GSBundle/Resources/views/Goldsprint/championship-tournament-rules.html.twig
<h4>Rules</h4>
<table class="table table-bordered table-condensed table-hover">
    <tr>
        <th>Championship rounds</th>
        <td>{{ entity.type.nbChampionshipRound }}</td>
    </tr>
    <tr>
        <th>Qualified players</th>
        <td>{{ entity.type.nbQualifiedPlayer }}</td>
    </tr>
    <tr>
        <th>Tournament</th>
        <td>Single elimination tournament - Random each turn</td>
    </tr>
</table>

src/Siriru/GSBundle/Resources/views/Goldsprint/championship.html.twig
{% set step = 0 %}
<table>
    {% for run in entity.type.runs %}
        {% if run.step != step %}
            <tr>
                <td colspan="3" style="text-align: center;">Round {{ step + 1}}</td>
            </tr>
            {% set step = run.step %}
        {% endif %}
        <tr>
            <td style="text-align: right;">{{ run.time1 | gstime }} &larr;&nbsp;</td>
            <td style="text-align: center;"><a href="{{ path('run_edit', {'id': run.id}) }}">{{ run }}</a></td>
            <td style="text-align: left;">&nbsp;&rarr; {{ run.time2 | gstime }}</td>
        </tr>
    {% endfor %}
</table>

src/Siriru/GSBundle/Resources/views/Goldsprint/edit.html.twig
{% extends '::base.html.twig' %}
{% form_theme edit_form with 'SiriruGSBundle:Form:fields.html.twig' %}
{% form_theme delete_form with 'SiriruGSBundle:Form:delete.html.twig' %}

{% block body -%}
    <h1>Goldsprint edit {{ form(delete_form) }}</h1>

    <table class="table table-bordered table-striped table-fixed table-condensed" style="width: 70%;" {{ block('widget_container_attributes') }}>
        {{ form_start(edit_form) }}
        {% if edit_form.parent is empty and form_errors(edit_form)|length > 0 %}
            <tr>
                <td colspan="2">
                    {{ form_errors(edit_form) }}
                </td>
            </tr>
        {% endif %}

        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-bookmark"></span> {{ form_label(edit_form.name) }}
            </td>
            <td>
                {{ form_errors(edit_form.name) }}
                {{ form_widget(edit_form.name) }}
            </td>
        </tr>
        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-map-marker"></span> {{ form_label(edit_form.location) }}
            </td>
            <td>
                {{ form_errors(edit_form.location) }}
                {{ form_widget(edit_form.location) }}
            </td>
        </tr>
        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-comment"></span> {{ form_label(edit_form.description) }}
            </td>
            <td>
                {{ form_errors(edit_form.description) }}
                {{ form_widget(edit_form.description) }}
            </td>
        </tr>
        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-calendar"></span> {{ form_label(edit_form.date) }}
            </td>
            <td>
                {{ form_errors(edit_form.date) }}
                {{ form_widget(edit_form.date) }}
            </td>
        </tr>
        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-user"></span> {{ form_label(edit_form.players) }}
            </td>
            <td>
                {{ form_errors(edit_form.players) }}
                {{ form_widget(edit_form.players) }}
            </td>
        </tr>
        {{ form_rest(edit_form) }}
        {{ form_end(edit_form) }}
    </table>

    <a href="{{ path('goldsprint') }}">
        <span class="glyphicon glyphicon-arrow-left"></span> Back to the list
    </a>
{% endblock %}

src/Siriru/GSBundle/Resources/views/Goldsprint/free-session-results.html.twig
<table class="table table-bordered table-condensed table-striped table-hover">
    <thead>
    <tr>
        <th>Player</th>
        <th>Best time</th>
    </tr>
    </thead>
    <tbody>
    {% for result in entity.type.results %}
    <tr>
        <td>{{ result.object }}</td>
        <td>{{ result.time | gstime }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

src/Siriru/GSBundle/Resources/views/Goldsprint/free-session-rules.html.twig
<h4>Rules</h4>
<table class="table table-bordered table-condensed table-hover">
    <tr>
        <th>Free session</th>
        <td>Try to beat the best run !</td>
    </tr>
</table>

src/Siriru/GSBundle/Resources/views/Goldsprint/free-session.html.twig
<h4>Runs</h4>
<table class="table table-bordered table-condensed table-hover">
    {% for run in entity.type.runs %}
        {{ include('SiriruGSBundle:Goldsprint:free-session-run.html.twig') }}
    {% endfor %}
</table>

{% if entity.finished != true %}<a href="{{ path('gs_run_new', { 'id': entity.id }) }}" class="btn btn-warning btn-sm" role="button">New run</a>{% endif %}

<script language="JavaScript">
    $(document).ready(function() {
        var times = [];
        $("td.time").each(function() {
            times.push($(this).attr('data-time'));
            times.sort(function(a,b){return a-b});
            $.unique(times);
        });
        var cpt = 1;
        for(var i=0; i<times.length; i++) {
            var standing = cpt;
            $("td.time[data-time=\""+times[i]+"\"]").each(function() {
                var value = "<small><strong>("+(standing)+")</strong></small>";
                if($(this).next().size() == 0) $(this).html($(this).text()+" "+value);
                else $(this).html(value+" "+$(this).text());
                cpt++;
            });
        }
    });
</script>

src/Siriru/GSBundle/Resources/views/Goldsprint/index.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Goldsprint list</h1>

    <table class="table table-bordered table-responsive table-striped table-condensed table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Location</th>
                <th>Created</th>
                <th>Started</th>
                <th>Finished</th>
                <th width="200">Type</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td>{{ entity.name }}</td>
                <td>{% if entity.date %}{{ entity.date|date('Y-m-d H:i:s') }}{% endif %}</td>
                <td>{{ entity.location }}</td>
                <td>{% if entity.created %}{{ entity.created|date('Y-m-d H:i:s') }}{% endif %}</td>
                <td>{% if entity.started %}<span class="label label-success">Yes</span>{% else %}<span class="label label-danger">No</span>{% endif %}</td>
                <td>{% if entity.finished %}<span class="label label-success">Yes</span>{% else %}<span class="label label-danger">No</span>{% endif %}</td>
                <td>{% if entity.type %}{{ entity.type.name }}{% else %}<span class="label label-danger">Not set</span>{% endif %}</td>
                <td>
                    <ul class="table-action">
                        <li>
                            <a href="{{ path('goldsprint_show', { 'id': entity.id }) }}">
                                <button type="button" class="btn btn-warning btn-xs">
                                    <span class="glyphicon glyphicon-search"></span> Show
                                </button>
                            </a>
                        </li>
                        <li>
                            <a href="{{ path('goldsprint_edit', { 'id': entity.id }) }}">
                                <button type="button" class="btn btn-warning btn-xs">
                                    <span class="glyphicon glyphicon-pencil"></span> Edit
                                </button>
                            </a>
                        </li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('goldsprint_new') }}" class="btn btn-primary btn-sm pull-right" role="button">
        <span class="glyphicon glyphicon-plus"></span> New Goldsprint
    </a>
    {% endblock %}

src/Siriru/GSBundle/Resources/views/Goldsprint/new.html.twig
{% extends '::base.html.twig' %}
{% form_theme form with 'SiriruGSBundle:Form:fields.html.twig' %}

{% block body -%}
    <h1>Goldsprint creation</h1>

    <table class="table table-bordered table-striped table-fixed table-condensed" style="width: 70%;" {{ block('widget_container_attributes') }}>
        {{ form_start(form) }}
        {% if form.parent is empty and form_errors(form)|length > 0 %}
            <tr>
                <td colspan="2">
                    {{ form_errors(form) }}
                </td>
            </tr>
        {% endif %}

        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-bookmark"></span> {{ form_label(form.name) }}
            </td>
            <td>
                {{ form_errors(form.name) }}
                {{ form_widget(form.name) }}
            </td>
        </tr>
        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-map-marker"></span> {{ form_label(form.location) }}
            </td>
            <td>
                {{ form_errors(form.location) }}
                {{ form_widget(form.location) }}
            </td>
        </tr>
        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-comment"></span> {{ form_label(form.description) }}
            </td>
            <td>
                {{ form_errors(form.description) }}
                {{ form_widget(form.description) }}
            </td>
        </tr>
        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-calendar"></span> {{ form_label(form.date) }}
            </td>
            <td>
                {{ form_errors(form.date) }}
                {{ form_widget(form.date) }}
            </td>
        </tr>
        <tr>
            <td class="strong" width="200">
                <span class="glyphicon glyphicon-user"></span> {{ form_label(form.players) }}
            </td>
            <td>
                {{ form_errors(form.players) }}
                {{ form_widget(form.players) }}
            </td>
        </tr>
        {{ form_rest(form) }}
        {{ form_end(form) }}
    </table>

    <a href="{{ path('goldsprint') }}">
        <span class="glyphicon glyphicon-arrow-left"></span> Back to the list
    </a>
{% endblock %}