src/Siriru/GSBundle/Entity/Run.php
<?php

namespace Siriru\GSBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="run")
 */
class Run
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $step;

    /**
     * @ORM\ManyToOne(targetEntity="Siriru\GSBundle\Entity\Player")
     * @ORM\JoinColumn(nullable=true)
     */
    protected $player1;

    /**
     * @ORM\ManyToOne(targetEntity="Siriru\GSBundle\Entity\Player")
     * @ORM\JoinColumn(nullable=true)
     */
    protected $player2;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $time1;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $time2;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $speed1;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $speed2;

    /**
     * @ORM\ManyToOne(targetEntity="Siriru\GSBundle\Entity\GoldsprintType", inversedBy="runs")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $type;

    /**
     * Constructor
     */
    public function __construct(Player $player1 = null, Player $player2 = null)
    {
        $this->player1 = $player1;
        $this->player2 = $player2;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set step
     *
     * @param integer $step
     * @return Run
     */
    public function setStep($step)
    {
        $this->step = $step;

        return $this;
    }

    /**
     * Get step
     *
     * @return integer 
     */
    public function getStep()
    {
        return $this->step;
    }

    /**
     * Set time1
     *
     * @param float $time1
     * @return Run
     */
    public function setTime1($time1 = null)
    {
        $this->time1 = $time1;

        return $this;
    }

    /**
     * Get time1
     *
     * @return float
     */
    public function getTime1()
    {
        return $this->time1;
    }

    /**
     * Set time2
     *
     * @param float $time2
     * @return Run
     */
    public function setTime2($time2 = null)
    {
        $this->time2 = $time2;

        return $this;
    }

    /**
     * Get time2
     *
     * @return float
     */
    public function getTime2()
    {
        return $this->time2;
    }

    /**
     * @param float $speed1
     * @return Run
     */
    public function setSpeed1($speed1)
    {
        $this->speed1 = $speed1;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSpeed1()
    {
        return $this->speed1;
    }

    /**
     * @param float $speed2
     * @return Run
     */
    public function setSpeed2($speed2)
    {
        $this->speed2 = $speed2;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSpeed2()
    {
        return $this->speed2;
    }


    /**
     * Set player1
     *
     * @param \Siriru\GSBundle\Entity\Player $player1
     * @return Run
     */
    public function setPlayer1(Player $player1 = null)
    {
        $this->player1 = $player1;

        return $this;
    }

    /**
     * Get player1
     *
     * @return \Siriru\GSBundle\Entity\Player 
     */
    public function getPlayer1()
    {
        return $this->player1;
    }

    /**
     * Set player2
     *
     * @param \Siriru\GSBundle\Entity\Player $player2
     * @return Run
     */
    public function setPlayer2(Player $player2 = null)
    {
        $this->player2 = $player2;

        return $this;
    }

    /**
     * Get player2
     *
     * @return \Siriru\GSBundle\Entity\Player 
     */
    public function getPlayer2()
    {
        return $this->player2;
    }

    /**
     * Get winner
     *
     * @return \Siriru\GSBundle\Entity\Player 
     */
    public function getWinner()
    {
        if($this->time1 != null and $this->time2 != null) {
            if($this->time1 == $this->time2) {
                if($this->speed1 > $this->speed2) return $this->player1;
                elseif($this->speed1 < $this->speed2) return $this->player2;
                else return null;
            }
            elseif($this->time1 < $this->time2) return $this->player1;
            else return $this->player2;
        }
        else return null;
    }

    /**
     * Set type
     *
     * @param \Siriru\GSBundle\Entity\GoldsprintType $type
     * @return Run
     */
    public function setType(GoldsprintType $type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return \Siriru\GSBundle\Entity\GoldsprintType 
     */
    public function getType()
    {
        return $this->type;
    }

    public function __toString()
    {
        $player2 = $this->player2 === null ? 'Ghost' : $this->player2;
        return $this->player1.' VS '.$player2;
    }

    public function getLooser()
    {
        $winner = $this->getWinner();
        if($winner) {
            if($winner == $this->player1) return $this->player2;
            else return $this->player1;
        }
        else return null;
    }

    public function getWinnerTime()
    {
        $winner = $this->getWinner();
        if($winner) {
            if($winner == $this->player1) return $this->time1;
            else return $this->time2;
        }
        else return 0;
    }

    public function getLooserTime()
    {
        $looser = $this->getLooser();
        if($looser) {
            if($looser == $this->player1) return $this->time1;
            else return $this->time2;
        }
        else return 0;
    }
}

src/Siriru/GSBundle/Form/GSTimeType.php
<?php

namespace Siriru\GSBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Siriru\GSBundle\Form\DataTransformer\GSTimeToNumberTransformer;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class GSTimeType extends AbstractType
{
    /**
     * @var ObjectManager
     */
    private $om;

    /**
     * @param ObjectManager $om
     */
    public function __construct(ObjectManager $om)
    {
        $this->om = $om;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $transformer = new GSTimeToNumberTransformer($this->om);
        $builder->addViewTransformer($transformer);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'invalid_message' => 'Invalid',
        ));
    }

    public function getParent()
    {
        return 'text';
    }

    public function getName()
    {
        return 'gs_time';
    }
}

src/Siriru/GSBundle/Form/RunType.php
<?php

namespace Siriru\GSBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class RunType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('player1', 'entity', array(
                'class' => 'SiriruGSBundle:Player',
                'property' => 'name',
                'expanded' => false,
                'multiple' => false,
                'required' => false
            ))
            ->add('player2', 'entity', array(
                'class' => 'SiriruGSBundle:Player',
                'property' => 'name',
                'expanded' => false,
                'multiple' => false,
                'required' => false
            ))
            ->add('time1', 'gs_time')
            ->add('time2', 'gs_time')
            ->add('speed1')
            ->add('speed2')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Siriru\GSBundle\Entity\Run'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'siriru_gsbundle_run';
    }
}

src/Siriru/GSBundle/Controller/RunController.php
<?php

namespace Siriru\GSBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Siriru\GSBundle\Entity\Run;
use Siriru\GSBundle\Form\RunType;

/**
 * Run controller.
 *
 * @Route("/run")
 */
class RunController extends Controller
{

    /**
     * Lists all Run entities.
     *
     * @Route("/", name="run")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('SiriruGSBundle:Run')->findAll();

        return array(
            'entities' => $entities,
        );
    }

    /**
     * Finds and displays a Run entity.
     *
     * @Route("/{id}", name="run_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SiriruGSBundle:Run')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Run entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Run entity.
     *
     * @Route("/{id}/edit", name="run_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SiriruGSBundle:Run')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Run entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a Run entity.
    *
    * @param Run $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Run $entity)
    {
        $form = $this->createForm(new RunType(), $entity, array(
            'action' => $this->generateUrl('run_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing Run entity.
     *
     * @Route("/{id}", name="run_update")
     * @Method("PUT")
     * @Template("SiriruGSBundle:Run:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SiriruGSBundle:Run')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Run entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('goldsprint_show', array('id' => $entity->getType()->getGoldsprint()->getId())));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a Run entity.
     *
     * @Route("/{id}", name="run_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('SiriruGSBundle:Run')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Run entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('run'));
    }

    /**
     * Creates a form to delete a Run entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('run_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm()
        ;
    }
}

src/Siriru/GSBundle/Resources/views/Run/edit.html.twig
{% extends '::base.html.twig' %}
{% form_theme edit_form with 'SiriruGSBundle:Form:fields.html.twig' %}

{% block body -%}
        <h1>Run edit</h1>
        <table class="table table-bordered table-striped table-fixed table-condensed" style="width: 50%;" {{ block('widget_container_attributes') }}>
            {{ form_start(edit_form) }}
            {% if edit_form.parent is empty and form_errors(edit_form)|length > 0 %}
                <tr>
                    <td colspan="2">
                        {{ form_errors(edit_form) }}
                    </td>
                </tr>
            {% endif %}

            <tr>
                <td class="strong" width="200">
                    <span class="glyphicon glyphicon-user"></span> {{ form_label(edit_form.player1) }}
                </td>
                <td>
                    {{ form_errors(edit_form.player1) }}
                    {{ form_widget(edit_form.player1) }}
                </td>
            </tr>
            <tr>
                <td class="strong" width="200">
                    <span class="glyphicon glyphicon-user"></span> {{ form_label(edit_form.player2) }}
                </td>
                <td>
                    {{ form_errors(edit_form.player2) }}
                    {{ form_widget(edit_form.player2) }}
                </td>
            </tr>
            <tr>
                <td class="strong" width="200">
                    <span class="glyphicon glyphicon-time"></span> {{ form_label(edit_form.time1) }}
                </td>
                <td>
                    {{ form_errors(edit_form.time1) }}
                    {{ form_widget(edit_form.time1) }}
                </td>
            </tr>
            <tr>
                <td class="strong" width="200">
                    <span class="glyphicon glyphicon-time"></span> {{ form_label(edit_form.time2) }}
                </td>
                <td>
                    {{ form_errors(edit_form.time2) }}
                    {{ form_widget(edit_form.time2) }}
                </td>
            </tr>
            <tr>
                <td class="strong" width="200">
                    <span class="glyphicon glyphicon-flash"></span> {{ form_label(edit_form.speed1) }}
                </td>
                <td>
                    {{ form_errors(edit_form.speed1) }}
                    {{ form_widget(edit_form.speed1) }}
                </td>
            </tr>
            <tr>
                <td class="strong" width="200">
                    <span class="glyphicon glyphicon-flash"></span> {{ form_label(edit_form.speed2) }}
                </td>
                <td>
                    {{ form_errors(edit_form.speed2) }}
                    {{ form_widget(edit_form.speed2) }}
                </td>
            </tr>
            {{ form_rest(edit_form) }}
            {{ form_end(edit_form) }}
        </table>

        <a href="{{ path('goldsprint_show', { 'id': entity.type.goldsprint.id }) }}">
            <span class="glyphicon glyphicon-arrow-left"></span> Back to the goldsprint
        </a>
{% endblock %}

src/Siriru/GSBundle/Resources/views/Run/index.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Run list</h1>

    <table class="records_list">
        <thead>
            <tr>
                <th>Id</th>
                <th>Step</th>
                <th>Time1</th>
                <th>Time2</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td><a href="{{ path('run_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                <td>{{ entity.step }}</td>
                <td>{{ entity.time1 }}</td>
                <td>{{ entity.time2 }}</td>
                <td>
                <ul>
                    <li>
                        <a href="{{ path('run_show', { 'id': entity.id }) }}">show</a>
                    </li>
                    <li>
                        <a href="{{ path('run_edit', { 'id': entity.id }) }}">edit</a>
                    </li>
                </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        <ul>
        <li>
            <a href="{{ path('run_new') }}">
                Create a new entry
            </a>
        </li>
    </ul>
    {% endblock %}

src/Siriru/GSBundle/Resources/views/Run/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Run {{ entity }}</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Step</th>
                <td>{{ entity.step }}</td>
            </tr>
            <tr>
                <th>{{ entity.player1 }}</th>
                <td>{{ entity.time1 }}</td>
            </tr>
            <tr>
                <th>{% if entity.player2 %}{{ entity.player2 }}{% else %}Ghost{% endif %}</th>
                <td>{{ entity.time2 }}</td>
            </tr>
            <tr>
                <th>Winner</th>
                <td>{{ entity.winner }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('goldsprint_show', { 'id': entity.type.goldsprint.id }) }}">
            Back to the goldsprint
        </a>
    </li>
    <li>
        <a href="{{ path('run_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
</ul>
{% endblock %}